### ISSUE TITLE
Building the MLRTVC Application together

### ISSUE THREAD

**Issue by sveneschlbeck** [sveneschlbeck/Multi-Language-RTVC#1]
@Dannypeja @Aatularyan @AsterTheWanderer @Fzr2k @CrazyPlaysHD @lavarith @Andredenise @wotulong @cryptoCommunitiesCONTROLfuture-RAOKindx @HirabayashiCallie @DimensionWarped @Archviz360 @francisco-renteria @AlexSteveChungAlvarez @mithisha @brcisna @PabloSandovalxtxt @alexpeattie @matheusfillipe @vanpelt @cforcomputer @cclauss @mathigatti @CorentinJ @akaitsuki-ii @LeonardsonCC @greatabel @Jinksi @sebiglesias @akozdev @musikalkemist @aydodo @SynapticSage @noahyoda @vidalmaxime @jason-h-35 @thecodeboss @iamgroot42 @leopard627 @mruettgers @berdakh @adilsoybali @EdwardELeininger @DanielLin94144 @PatentLobster

Dear fans of the **Voice Cloning Community**,

since we are all interested in Voice Cloning or Audio Engineering overall and all have
either used or co-developed the ``Real-Time-Voice-Cloning`` repo, we are well aware, that
the repository is not maintained anymore and lacks structure, meaning that many errors stay,
issues cannot get handled and the documentation is unsatisfying.

For those and more reasons, I have decided to begin a new project, aiming to provide
the functionality of ``Real-Time-Voice-Cloning`` but enhancing it by adding support
for other languages, taking multiple developers/maintainers abord and writing a good
and clear documentation that explains both the theory behind and the application of
the code.

Since I wanted to wait for an initial response, I have not yet begun structuring the
repository (except for some basics) but I have a few things in mind that need to be
taken care of if we want to improve the original repo:

1. Writing a documentation that can actually help beginners (tricky, needs to be done
by someone who really understands the theory of pre-processing, spectrograms, etc.). First,
a wiki structure needs to be discussed/drafted before actually writing it with all its
sections (Theory, Prerequesites, Download, Learning, Training, Using GUI, etc.)
2. Structuring the directory hierarchy (lots of loose scripts in the old repo, maybe
structuring it differently/cleaner -> would mean code adaption though)  
3. Adding pre-trained models for different languages (I am working on a German model
myself at the moment, could take some time though)  
4. Developing a well-oiled work routine where issues get handled, new ideas discussed
and things done.

It would be really sad to see a good idea end on the siding just for lack-of-maintenance
reasons.

I am waiting for responses...

Greetings
Sven

**Comment by AsterTheWanderer** [comment]
Looks cool, count me in. I'm quite new to this stuff but I can help with adding pre-trained models for other languages. Learning a bunch of new stuff looks fun.

**Comment by sveneschlbeck** [comment]
@AsterTheWanderer Great, I think a lot of us are learning by doing, so that's okay. At the beginning, there will be a lot of tasks that require a good overview, structuring and doc skills more than actual devs, even though that will come too, once enough people join...

**Comment by AlexSteveChungAlvarez** [comment]
Right now I think I am finishing to train the spanish model for the synthesizer (it already achieved 100k steps! But for some audios it still cuts the text, I don't know why...). I forked this repo in case something bad happened to it. I am very interested into sharing the results with all of you! The only thing is that I don't know if will have much time to contribute on January, but I will still stay tunned. I want to be part of the MLRTVC, I think on February I will be able to work on it with you!

**Comment by sveneschlbeck** [comment]
@AlexSteveChungAlvarez Great, thanks for the input. A Spanish model would be great, apart from English, that's probably the one people will be most interested in.
There's no time pressure, I will be busy the next weeks, too. But step by step, we can really build this :)

**Comment by Dannypeja** [comment]
Very cool initiative! Thank you Sven. I was fiddeling with that thought as well but my programming skills are far from really good contributions. But I like trying out and testing. So count me in. I will be experimenting further. 

I would suggest  building a community on discord as well: https://discord.gg/zWqjw6M38G
I launched a Server a couple of days ago. 
That way we can discuss things faster and won't clutter issues with repeating help requests.
I am more than open to share administrative/moderative access of the server with motivated contributors of this group here.

**Comment by sveneschlbeck** [comment]
@Dannypeja Great input, all help is welcome :) The discord server is a great idea. This does indeed seem to be a good way of communicating inside the team.

**Comment by Dannypeja** [comment]
Not only inside the team but also for a future community of interested spectators :) 
Even stuff like this could be quickly moved over there.

**Comment by sveneschlbeck** [comment]
@Dannypeja Communication both for the team and in terms of support, help, outreach is very import. You seem to be quite well at handling/keeping an overview about information flow, that's nice.

**Comment by Dannypeja** [comment]
I am far from experienced in both, python programming/machine learning and discord administration ^^ 
We will Learn a lot..
I suggest we slowly move the thread over there. I have created a private channel for the small group of maintainers/ contributors. Send me a dm on the channel if you wish to be a part of that group. More or less it’s mirroring Svens question on this issue :)

**Comment by raccoonML** [comment]
It makes me very happy to see all this interest in continuing the development of the project. I am a long-time RTVC user and experienced in its use (training models, tweaking model architectures). Please let me know if I can contribute anything.

**Comment by sveneschlbeck** [comment]
@raccoonML Great, thanks a lot for your interest, your expertise is well-needed.

We could need your knowledge the most for restructuring the repo. Since you used it already, you may know how the different models depend upon each other. We already discussed some of this on the discord server but I would be happy to slowly shift towards GitHub Discussions.

Also, since you already trained models, you are probable the best person to write a detailed documentation about that process. We need yet to decide how the docs should look like...
